import math
from typing import Dict, Literal, Optional
from pydantic import BaseModel, Field, field_validator


class RouterResult(BaseModel):
    selected_expert: Literal["blending", "diffusion", "frequency", "texture"]
    selected_alias: Literal["Blending", "Diffusion", "Frequency", "Texture"]
    router_confidence: float = Field(..., ge=0.0, le=1.0)
    margin: float = Field(..., ge=0.0, le=1.0)


class ExpertResult(BaseModel):
    name: Literal["blending", "diffusion", "frequency", "texture"]
    raw_score: float
    calibrated_score: float = Field(..., ge=0.0, le=1.0)
    score_direction: str = "fake_probability"


class FinalResult(BaseModel):
    verdict: Literal["REAL", "FAKE"]
    fake_probability: float = Field(..., ge=0.0, le=1.0)
    real_probability: float = Field(..., ge=0.0, le=1.0)
    continuous_score: float = Field(..., ge=0.0, le=1.0)
    decision_threshold: float = 0.5
    explanation: Optional[str] = Field(None, description="Explanation text only if generated by the model")

    @field_validator("fake_probability", "real_probability", "continuous_score", mode="before")
    @classmethod
    def validate_finite_and_non_bool(cls, v):
        if isinstance(v, bool):
            raise ValueError("Score cannot be a boolean value")
        if not isinstance(v, (int, float)):
            raise ValueError(f"Score must be numeric, got {type(v).__name__}")
        f_val = float(v)
        if not math.isfinite(f_val):
            raise ValueError(f"Score must be finite, got {f_val}")
        if not (0.0 <= f_val <= 1.0):
            raise ValueError(f"Score must be in range [0, 1], got {f_val}")
        return f_val

    @field_validator("real_probability")
    @classmethod
    def validate_normalization(cls, v, info):
        fake_prob = info.data.get("fake_probability")
        if fake_prob is not None:
            if abs((v + fake_prob) - 1.0) > 1e-4:
                raise ValueError(f"Pairwise probabilities must sum to 1.0, got {v + fake_prob}")
        return v


class ImageAnalyzeResponse(BaseModel):
    request_id: str
    status: Literal["ok"] = "ok"
    media_type: Literal["image"] = "image"
    router: RouterResult
    expert: ExpertResult
    final: FinalResult
    timing_ms: Dict[str, float]
    provenance: Dict[str, str]
